-- Current SCP Alliance dossiers and weekly schedule.
-- Safe to run again: members are matched by code and schedules by stable UUID.

begin;

insert into public.members (
  id, code, name, role, role_groups, roster_type, clearance, alias, unique_text,
  track, strengths, stats, photo_path, sort_order, published
)
values
  (
    '10000000-0000-4000-8000-000000000013',
    'SCP-013',
    '[ TXD | WMORI ]',
    'Assault Squad',
    array['assault']::text[],
    'alliance',
    'CLEARANCE: LEVEL Ω',
    '"The Phantom Strike"',
    'Selalu mengeksekusi entry pertama tanpa menunggu info caller — gaya "silent breach" yang membuat lawan kehilangan tempo sejak ronde pertama.',
    '[{"clan":"JAC","role":"Vehicle","year":"2025 – 2025"},{"clan":"TREX","role":"Vehicle","year":"2025 – 2025"},{"clan":"NOTS","role":"Vehicle (Commander)","year":"2025 – 2026"},{"clan":"TXDNR","role":"Vehicle (Commander)","year":"2025 – Now"}]'::jsonb,
    '["Refleks tembak presisi tinggi","Penguasaan peta agresif","Konsistensi clutch 1vX","Spray control elite"]'::jsonb,
    '[["VEHICLE",100],["SHOOTING",75],["SURVIVAL",80],["CO-OP",78],["OBJECTIVE",65]]'::jsonb,
    null,
    1,
    true
  ),
  (
    '10000000-0000-4000-8000-000000000048',
    'SCP-048',
    '[ NOTS 丶Alpin鋼 ]',
    'Tankerch Sankai',
    array['vehicle']::text[],
    'alliance',
    'CLEARANCE: LEVEL VII',
    '"Iron Dome Vanguard"',
    'Mampu menahan berbagai hantaman Rudal Balistik musuh',
    '[{"clan":"NOTS","role":"Loyality III","year":"2025 – Now"},{"clan":"NOTS REBORN DFNC S2","role":"IGL Squad","year":"2026 – 2026"}]'::jsonb,
    '["Mampu memaksimalkan kemampuan kendaraan tempur","Dapat memprediksi pergerakan kendaraan musuh","Siap menjadi badan utama infantry","Pelindung sektor vital fraksi"]'::jsonb,
    '[["VEHICLE",100],["SHOOTING",73],["SURVIVAL",70],["CO-OP",73],["OBJECTIVE",51]]'::jsonb,
    null,
    2,
    true
  ),
  (
    '10000000-0000-4000-8000-000000000051',
    'SCP-051',
    '[ RenSCP ]',
    'The Squadron',
    array['vehicle']::text[],
    'pure',
    'CLEARANCE: LEVEL VI',
    '"RRQEVOSNOTSAE"',
    'Membaca pola rotasi musuh lebih cepat dari siapa pun dan menyusun ulang strategi squad secara real-time.',
    '[{"clan":"WG","role":"Casual","year":"2025 – 2025"},{"clan":"PDR","role":"Destroyer","year":"2025 – 2025"},{"clan":"NOTS","role":"Flanker","year":"2025 – Now"}]'::jsonb,
    '["Adaptasi peran fleksibel","Pembacaan rotasi musuh","Eksekusi taktik cepat","Komunikasi jernih"]'::jsonb,
    '[["VEHICLE",100],["SHOOTING",62],["SURVIVAL",71],["CO-OP",67],["OBJECTIVE",60]]'::jsonb,
    null,
    3,
    true
  ),
  (
    '10000000-0000-4000-8000-000000000054',
    'SCP-054',
    '[ NOTS 丶NaaSCP54 ]',
    'Steel Keeper',
    array['vehicle']::text[],
    'alliance',
    'CLEARANCE: LEVEL VII',
    '"The Bulwark"',
    'Spesialis hold site — pernah mempertahankan bomb-site sendirian melawan serangan penuh tanpa kehilangan posisi.',
    '[{"clan":"NOTS Squad","role":"Anchor","year":"2020 – 2023"},{"clan":"S.C.P Alliance","role":"Steel Keeper","year":"2023 – Aktif"}]'::jsonb,
    '["Anchor site tak tergoyahkan","Manajemen utility hebat","Tembakan defensif akurat","Tenang di bawah tekanan"]'::jsonb,
    '[["VEHICLE",70],["SHOOTING",82],["SURVIVAL",95],["CO-OP",85],["OBJECTIVE",92]]'::jsonb,
    null,
    4,
    true
  ),
  (
    '10000000-0000-4000-8000-000000000044',
    'SCP-044',
    '[ NOTS 丶KoazyNXS ]',
    'Tactical Tanker',
    array['vehicle']::text[],
    'alliance',
    'CLEARANCE: LEVEL VI',
    '"Breach Hammer"',
    'Membuka jalan masuk dengan timing utility yang sempurna — gerbang pembuka setiap eksekusi tim.',
    '[{"clan":"NXS Gaming","role":"Initiator","year":"2021 – 2023"},{"clan":"S.C.P Alliance","role":"Tactical Tanker","year":"2023 – Aktif"}]'::jsonb,
    '["Timing utility presisi","Initiator agresif","Map control kuat","Koordinasi push"]'::jsonb,
    '[["VEHICLE",85],["SHOOTING",80],["SURVIVAL",84],["CO-OP",88],["OBJECTIVE",90]]'::jsonb,
    null,
    5,
    true
  ),
  (
    '10000000-0000-4000-8000-000000000012',
    'SCP-012',
    '[ NOTS 丶Ndan3NXS ]',
    'The Squadron',
    array['vehicle']::text[],
    'alliance',
    'CLEARANCE: LEVEL VI',
    '"Twin Blade"',
    'Bermain berpasangan dengan sinkronisasi nyaris telepatik — dua orang, satu gerakan.',
    '[{"clan":"NXS Gaming","role":"Duo Support","year":"2021 – 2023"},{"clan":"S.C.P Alliance","role":"The Squadron","year":"2023 – Aktif"}]'::jsonb,
    '["Sinergi duo elite","Trade-kill cepat","Crossfire disiplin","Posisi suportif"]'::jsonb,
    '[["VEHICLE",76],["SHOOTING",83],["SURVIVAL",80],["CO-OP",96],["OBJECTIVE",84]]'::jsonb,
    null,
    6,
    true
  ),
  (
    '10000000-0000-4000-8000-000000000022',
    'SCP-022',
    '[ NOTSJessSCP22 ]',
    'Engineer',
    array['engineer']::text[],
    'pure',
    'CLEARANCE: LEVEL V',
    '"The Vulcan"',
    'Bisa mengontrol Loitering di celah yang sempit.',
    '[{"clan":"NOTS","role":"Suave V","year":"2025 – Now"},{"clan":"NOTS","role":"Engineer Flanker","year":"2025 – Now"}]'::jsonb,
    '["Saat medan perang hancur, aku membangun","Saat mesin berhenti, aku menghidupkan","Saat harapan padam, aku menempa jalan"]'::jsonb,
    '[["VEHICLE",90],["SHOOTING",70],["SURVIVAL",68],["CO-OP",90],["OBJECTIVE",60]]'::jsonb,
    null,
    7,
    true
  ),
  (
    '10000000-0000-4000-8000-000000000018',
    'SCP-018',
    '[ NOTS 丶FinzNXS ]',
    'Engineer Support',
    array['engineer']::text[],
    'alliance',
    'CLEARANCE: LEVEL V',
    '"Lifeline"',
    'Selalu hadir di momen kritis untuk menyokong rekan — penopang yang menjaga tim tetap hidup.',
    '[{"clan":"NXS Gaming","role":"Support","year":"2022 – 2024"},{"clan":"S.C.P Alliance","role":"Engineer Support","year":"2024 – Aktif"}]'::jsonb,
    '["Support timing sempurna","Resource management","Backup posisi solid","Disiplin tim"]'::jsonb,
    '[["VEHICLE",82],["SHOOTING",73],["SURVIVAL",84],["CO-OP",93],["OBJECTIVE",80]]'::jsonb,
    null,
    8,
    true
  ),
  (
    '10000000-0000-4000-8000-000000000017',
    'SCP-017',
    '[ NOTS 丶RimuNXS ]',
    'Engineer Recon',
    array['engineer', 'recon']::text[],
    'alliance',
    'CLEARANCE: LEVEL V',
    '"The Eye"',
    'Membaca pergerakan musuh dari jejak sekecil apa pun — radar hidup yang jarang salah.',
    '[{"clan":"NXS Gaming","role":"Recon","year":"2022 – 2024"},{"clan":"S.C.P Alliance","role":"Engineer Recon","year":"2024 – Aktif"}]'::jsonb,
    '["Intel-gathering tajam","Pembacaan minimap","Info call akurat","Positioning cerdas"]'::jsonb,
    '[["VEHICLE",84],["SHOOTING",78],["SURVIVAL",80],["CO-OP",88],["OBJECTIVE",90]]'::jsonb,
    null,
    9,
    true
  ),
  (
    '10000000-0000-4000-8000-000000000027',
    'SCP-027',
    '[ ICE丨UrYuuVG ]',
    'Anomaly Recon',
    array['recon']::text[],
    'alliance',
    'CLEARANCE: LEVEL VI',
    '"Cold Specter"',
    'Bergerak senyap di flank dan muncul dari sudut tak terduga — anomali yang sulit dilacak musuh.',
    '[{"clan":"ICE Esports","role":"Lurker","year":"2021 – 2023"},{"clan":"S.C.P Alliance","role":"Anomaly Recon","year":"2023 – Aktif"}]'::jsonb,
    '["Flank tak terdeteksi","Timing serangan brilian","Info denial musuh","Clutch lurker"]'::jsonb,
    '[["VEHICLE",80],["SHOOTING",86],["SURVIVAL",88],["CO-OP",72],["OBJECTIVE",84]]'::jsonb,
    null,
    10,
    true
  ),
  (
    '10000000-0000-4000-8000-000000000119',
    'SCP-119',
    '[ SCP°119 ]',
    'Tactical Mind',
    array['assault']::text[],
    'pure',
    'CLEARANCE: LEVEL VIII',
    '"The Strategist"',
    'Otak taktik tim — merancang draft, mid-round call, dan adaptasi anti-strat yang menentukan kemenangan.',
    '[{"clan":"Vanguard Tactics","role":"In-Game Leader","year":"2019 – 2022"},{"clan":"S.C.P Alliance","role":"Tactical Mind","year":"2022 – Aktif"}]'::jsonb,
    '["Kepemimpinan in-game","Strategi & draft jitu","Mid-round adaptation","Manajemen mental tim"]'::jsonb,
    '[["VEHICLE",78],["SHOOTING",82],["SURVIVAL",85],["CO-OP",92],["OBJECTIVE",96]]'::jsonb,
    null,
    11,
    true
  ),
  (
    '10000000-0000-4000-8000-000000000099',
    'SCP-099',
    '[ SEALxKeenan舎 ]',
    'Recon Striker',
    array['recon']::text[],
    'alliance',
    'CLEARANCE: LEVEL VI',
    '"Silent Tide"',
    'Spesialis infiltrasi senyap — masuk lebih dulu, membuka informasi, dan menutup celah sebelum musuh sadar.',
    '[{"clan":"SEAL Division","role":"Recon","year":"2022 – 2024"},{"clan":"S.C.P Alliance","role":"Recon Striker","year":"2024 – Aktif"}]'::jsonb,
    '["Infiltrasi senyap","Pembacaan posisi musuh","Eksekusi flank presisi","Disiplin info call"]'::jsonb,
    '[["VEHICLE",80],["SHOOTING",85],["SURVIVAL",84],["CO-OP",86],["OBJECTIVE",88]]'::jsonb,
    null,
    12,
    true
  )
on conflict (code) do update
set
  name = excluded.name,
  role = excluded.role,
  role_groups = excluded.role_groups,
  roster_type = excluded.roster_type,
  clearance = excluded.clearance,
  alias = excluded.alias,
  unique_text = excluded.unique_text,
  track = excluded.track,
  strengths = excluded.strengths,
  stats = excluded.stats,
  photo_path = excluded.photo_path,
  sort_order = excluded.sort_order,
  published = excluded.published;

insert into public.schedule_entries (
  id, schedule_kind, operation_type, title, opponent, status,
  weekday, event_date, start_time, end_time, end_open,
  details, notes, sort_order, published
)
values
  (
    '20000000-0000-4000-8000-000000000001',
    'weekly',
    'training',
    'SCP — Latihan internal divisi',
    null,
    'scheduled',
    5,
    null,
    '20:00',
    '22:00',
    false,
    'Latihan internal divisi',
    'Koordinasi & evaluasi tim',
    1,
    true
  ),
  (
    '20000000-0000-4000-8000-000000000002',
    'weekly',
    'scrim',
    'SCP — Scrim Sabtu (perlu konfirmasi)',
    null,
    'seeking_opponent',
    6,
    null,
    '19:00',
    null,
    true,
    'Lawan belum ditentukan',
    'Terbuka untuk tantangan clan',
    2,
    true
  ),
  (
    '20000000-0000-4000-8000-000000000003',
    'weekly',
    'scrim',
    'SCP — Scrim Minggu (perlu konfirmasi)',
    null,
    'seeking_opponent',
    0,
    null,
    '15:00',
    '18:00',
    false,
    'Lawan belum ditentukan',
    'Terbuka untuk tantangan clan',
    3,
    true
  )
on conflict (id) do update
set
  schedule_kind = excluded.schedule_kind,
  operation_type = excluded.operation_type,
  title = excluded.title,
  opponent = excluded.opponent,
  status = excluded.status,
  weekday = excluded.weekday,
  event_date = excluded.event_date,
  start_time = excluded.start_time,
  end_time = excluded.end_time,
  end_open = excluded.end_open,
  details = excluded.details,
  notes = excluded.notes,
  sort_order = excluded.sort_order,
  published = excluded.published;

commit;
